application: qproject-webapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets
  application_readable: true

- url: /views
  static_dir: views
  application_readable: true

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
